# Generated by Django 3.2.25 on 2024-04-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RentBook',
            fields=[
                ('book_id', models.CharField(max_length=15)),
                ('book_name', models.CharField(max_length=200)),
                ('student_name', models.CharField(max_length=100)),
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
