# Generated by Django 3.2.25 on 2024-05-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='session_id',
            field=models.CharField(default='6041hpowxj2l6mjtsr493heayxhmlve1', max_length=200),
            preserve_default=False,
        ),
    ]
