# Generated by Django 3.2.25 on 2024-05-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20240512_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user_id',
            new_name='user',
        ),
    ]
