# Generated by Django 3.2.25 on 2024-07-16 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20240708_1946'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookSKU',
        ),
    ]
